import { useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Icon, ItineraryCategoryIcon } from '../../components/icons/Icon';
import { StatusNotice } from '../../components/primitives/Objects';
import { usePlace, useTripDays } from '../trips/queries';
import { useTripData } from '../../app/TripDataContext';
import './place-flow.css';

function Header({title,back}:{title:string;back:string}){return <header className="flow-header"><Link to={back}><Icon name="back" size={20}/>返回</Link><h1>{title}</h1></header>}

export function PlaceDetailsPage(){const {tripId,placeId}=useParams();const {data:place,isLoading,isError,refetch}=usePlace(tripId,placeId);if(isLoading)return <main className="phone-shell flow-page"><Header title="景點詳情" back={`/trips/${tripId}/places`}/><section className="flow-body"><p className="state-card">正在載入景點資訊…</p></section></main>;if(isError||!place)return <main className="phone-shell flow-page"><Header title="景點詳情" back={`/trips/${tripId}/places`}/><section className="flow-body"><p className="state-card is-error">無法載入景點。<button onClick={()=>void refetch()}>重試</button></p></section></main>;return <main className="phone-shell flow-page"><Header title="景點詳情" back={`/trips/${tripId}/places`}/><section className="flow-body"><div className="place-detail-hero"><ItineraryCategoryIcon category={place.category}/><span>{place.categoryLabel} · {place.region}</span></div><h2 className="detail-title">{place.name}</h2><p className="detail-lead">適合安排在景福宮與三清洞之間，建議預留 {place.suggestedDurationMinutes} 分鐘慢慢散步。</p><div className="detail-facts"><span>評分 <strong>{place.rating}</strong></span><span>距離上一站 <strong>{place.travelMinutes} 分</strong></span></div><Link className="primary-link" to={`/trips/${tripId}/plan/add/${place.id}`}>加入行程</Link></section></main>}

export function EditItineraryPage(){const {tripId,itemId}=useParams();const navigate=useNavigate();const {days,updateItem}=useTripData();const item=Object.values(days).flat().find(entry=>entry.id===itemId);const [saving,setSaving]=useState(false);const [failed,setFailed]=useState(false);const [title,setTitle]=useState(item?.title??(itemId==='item-flight'?'桃園至仁川':'國立民俗博物館'));const [duration,setDuration]=useState(item?.durationMinutes??60);const save=async()=>{if(!item)return setFailed(true);setSaving(true);setFailed(false);try{await updateItem(item.id,item.version,{title,durationMinutes:duration});navigate(`/trips/${tripId}/plan?day=${item.tripDayId}&updated=1`)}catch{setFailed(true)}finally{setSaving(false)}};return <main className="phone-shell flow-page"><Header title="編輯行程" back={`/trips/${tripId}/plan`}/><section className="flow-body">{failed&&<StatusNotice type="conflict" title="儲存失敗">變更已復原，請載入最新版後重試。</StatusNotice>}<label className="info-field">行程名稱<input value={title} onChange={event=>setTitle(event.target.value)}/></label><div className="field-grid"><label>停留時間<select value={duration} onChange={event=>setDuration(Number(event.target.value))}><option value="30">30 分</option><option value="60">1 小時</option><option value="90">1.5 小時</option></select></label></div><label className="notes-field">備註<textarea defaultValue={item?.meta??'記得提前確認營業時間'}/></label><button className="primary-action" disabled={saving||!item} aria-busy={saving} onClick={()=>void save()}>{saving?'正在儲存…':'儲存變更'}</button></section></main>}

export function QuickAdjustPage(){const {tripId}=useParams();const [params]=useSearchParams();const navigate=useNavigate();const {data:days=[]}=useTripDays(tripId);const [selected,setSelected]=useState(params.get('day')??days[0]?.id??'');return <main className="phone-shell flow-page"><Header title="快速調整" back={`/trips/${tripId}/plan`}/><section className="flow-body"><p className="detail-lead">選擇要移動的日期，系統會保留固定預約並重新排列可調整行程。</p><div className="day-picker">{days.map(day=><button key={day.id} className={selected===day.id?'is-selected':''} onClick={()=>setSelected(day.id)}>Day {day.sortOrder}</button>)}</div><div className="quick-options"><button><Icon name="clock"/>延後 30 分鐘<span>固定預約不移動</span></button><button><Icon name="plan"/>壓縮空檔<span>保留原有順序</span></button><button><Icon name="refresh"/>重新最佳化<span>依距離與營業時間排序</span></button></div><button className="primary-action" disabled={!selected} onClick={()=>navigate(`/trips/${tripId}/plan?day=${selected}&updated=1`)}>預覽調整結果</button></section></main>}

export function FlightReschedulePage(){const {tripId,itemId}=useParams();const navigate=useNavigate();const{days,updateItem}=useTripData();const item=Object.values(days).flat().find(entry=>entry.id===itemId);const [choice,setChoice]=useState('shift');const [saving,setSaving]=useState(false);const [failed,setFailed]=useState(false);const submit=async()=>{if(!item)return setFailed(true);setSaving(true);try{await updateItem(item.id,item.version,{meta:`${item.meta} · 航班異動處理：${choice}`});navigate(`/trips/${tripId}/plan?day=${item.tripDayId}&updated=1`)}catch{setFailed(true)}finally{setSaving(false)}};return <main className="phone-shell flow-page"><Header title="航班異動調整" back={`/trips/${tripId}/plan`}/><section className="flow-body"><StatusNotice type="warning" title="航班時間已變更">{itemId??'航班'} 延後 1 小時 20 分，將影響抵達後兩段行程。</StatusNotice>{failed&&<StatusNotice type="conflict" title="套用失敗">變更已復原，請重新載入後再試。</StatusNotice>}<div className="affected-timeline"><strong>受影響行程</strong><span>15:30 飯店入住</span><span>17:00 明洞晚餐</span></div>{[['shift','自動順延','保留所有行程並順延時間'],['holding','移至暫存區','先保留晚餐，抵達後再安排'],['manual','手動調整','回到編排頁自行處理']].map(([value,title,meta])=><label key={value} className={`resolution ${choice===value?'is-selected':''}`}><input type="radio" name="flight-choice" checked={choice===value} onChange={()=>setChoice(value)}/><span><strong>{title}</strong><small>{meta}</small></span></label>)}<button className="primary-action" disabled={saving||!item} aria-busy={saving} onClick={()=>void submit()}>{saving?'正在重新安排…':'套用並通知旅伴'}</button></section></main>}
