import { useEffect,useState } from 'react';
import { Link,useNavigate,useParams,useSearchParams } from 'react-router-dom';
import { useTripData } from '../../app/TripDataContext';
import { Icon } from '../../components/icons/Icon';
import { Button } from '../../components/primitives/Button';
import { StatusNotice } from '../../components/primitives/Objects';
import { useTripDays,useTripRole } from '../trips/queries';
import './planner.css';
const time=(value:string)=>new Intl.DateTimeFormat('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Seoul'}).format(new Date(value));
export function PlannerPage(){
  const{tripId}=useParams();const navigate=useNavigate();const[params]=useSearchParams();const{data:tripDays=[]}=useTripDays(tripId);const{data:role='viewer'}=useTripRole(tripId);const canEdit=role==='owner'||role==='admin'||role==='editor';
  const[dayId,setDayId]=useState(params.get('day')??'');const[drag,setDrag]=useState<{dayId:string;index:number;itemId:string}|null>(null);const[deleteId,setDeleteId]=useState<string|null>(null);const{days,syncState,error,loadDay,move,moveAcross,removeItem,retry}=useTripData();
  useEffect(()=>{if(!dayId&&tripDays[0])setDayId(tripDays[0].id)},[dayId,tripDays]);useEffect(()=>{tripDays.forEach(day=>{void loadDay(day.id)})},[loadDay,tripDays]);
  const rows=days[dayId]??[];const selected=tripDays.find(({id})=>id===dayId);const target=rows.find(item=>item.id===deleteId);
  const notice=syncState==='saving'?<StatusNotice type="warning" title="正在儲存">變更正在同步給旅伴。</StatusNotice>:syncState==='conflict'?<StatusNotice type="conflict" title={error?.code==='SORT_KEY_CONFLICT'?'排序衝突':'版本衝突'}>{error?.message??'其他旅伴已更新行程，本次變更已復原。'} <button onClick={()=>void retry()}>載入最新版</button></StatusNotice>:syncState==='offline'?<StatusNotice type="warning" title="目前離線">{error?.message??'變更已復原；連線恢復後請重試。'} <button onClick={()=>void retry()}>重試</button></StatusNotice>:syncState==='failed'?<StatusNotice type="conflict" title={error?.code==='FORBIDDEN_ROLE'?'沒有修改權限':error?.code==='AUTH_REQUIRED'?'登入已失效':'儲存失敗'}>{error?.message??'變更已復原。'} {error?.retryable&&<button onClick={()=>void retry()}>重試</button>}</StatusNotice>:null;
  return <main className="phone-shell planner"><header className="planner-header"><Link to={`/trips/${tripId}/today`}><Icon name="back" size={16}/>返回</Link><h1>安排 Day {selected?.sortOrder??'—'}</h1><p>{selected?.title??'載入旅程資料中'}</p></header><section className="planner-body">{params.get('updated')&&<StatusNotice type="success" title="已更新行程">停留時間已縮短，其他行程保持不變。</StatusNotice>}{!canEdit&&<StatusNotice type="warning" title="僅能檢視">你的 Viewer 權限不能修改行程。</StatusNotice>}{notice}<div className="day-switcher" role="tablist" aria-label="選擇旅行日期">{tripDays.map(day=><button key={day.id} role="tab" aria-selected={day.id===dayId} className={day.id===dayId?'is-selected':''} onClick={()=>setDayId(day.id)}>{`Day ${day.sortOrder}`}</button>)}</div>{canEdit&&drag&&tripDays.filter(day=>day.id!==drag.dayId).map(day=><button className="cross-day-drop" key={day.id} onDragOver={event=>event.preventDefault()} onDrop={()=>{void moveAcross(drag.dayId,day.id,drag.itemId,(days[day.id]??[]).length);setDrag(null)}}>移到 Day {day.sortOrder}</button>)}<div className="planner-rows" aria-live="polite">{!rows.length&&<p className="empty-day">這一天還沒有行程。</p>}{rows.map((item,index)=><article key={item.id} className={`planner-row ${drag?.itemId===item.id?'is-dragging':''}`} draggable={canEdit&&!item.fixed} onDragStart={()=>setDrag({dayId,index,itemId:item.id})} onDragEnd={()=>setDrag(null)} onDragOver={event=>event.preventDefault()} onDrop={()=>{if(drag&&drag.dayId===dayId)void move(dayId,drag.index,index);else if(drag)void moveAcross(drag.dayId,dayId,drag.itemId,index);setDrag(null)}}><button className="drag-handle" aria-label={`拖曳${item.title}`} disabled={!canEdit||item.fixed}><Icon name={item.fixed?'lock':'drag'} size={20}/></button><div><strong>{time(item.startsAt)}　{item.title}</strong><span>{item.meta}</span></div><div className="row-actions"><button aria-label={`${item.title}上移`} disabled={!canEdit||index===0||item.fixed} onClick={()=>void move(dayId,index,index-1)}>上</button><button aria-label={`刪除${item.title}`} disabled={!canEdit||item.fixed} onClick={()=>setDeleteId(item.id)}><Icon name="delete" size={16}/></button></div></article>)}</div><Button size="large" className="planner-cta" disabled={!canEdit} onClick={()=>navigate(`/trips/${tripId}/places`)}>尋找景點並加入行程</Button></section>{target&&<div className="confirm-backdrop" role="presentation"><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">刪除「{target.title}」？</h2><p>刪除後會立即同步給旅伴。</p><div><button onClick={()=>setDeleteId(null)}>取消</button><button className="danger" onClick={()=>void removeItem(target).then(()=>setDeleteId(null))}>確認刪除</button></div></section></div>}</main>;
}
