import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useExpenses, useTrip, useTripDays, useTripMembers } from './queries';
import { Icon } from '../../components/icons/Icon';
import './management.css';
import './budget.css';
const roleLabel={owner:'擁有者',admin:'管理員',editor:'可編輯',viewer:'僅檢視'} as const;
export function PeoplePage(){const {tripId}=useParams();const {data:members=[]}=useTripMembers(tripId);return <main className="mobile-page people-page"><Link className="back-link" to={`/trips/${tripId}/overview`}><Icon name="back" size={16}/>旅程總覽</Link><h1>旅伴與權限</h1><p className="lead">一起規劃、同步備註，也能控制誰可以修改行程。</p><section className="invite-card"><span>旅行邀請碼</span><strong>SEOUL-0826</strong><small>有效期限：8 月 31 日 · 可隨時停用</small></section><h2>{members.length} 位旅伴</h2><div className="member-list">{members.map((member,index)=><article key={member.userId}><span className={`member-avatar avatar-${index}`}>{member.displayName.slice(-1)}</span><div><strong>{member.displayName}</strong><small>{roleLabel[member.role]}</small></div><button aria-label={`${member.displayName}更多選項`}><Icon name="more"/></button></article>)}</div><aside className="privacy-note"><strong>隱私提醒</strong><span>只有受邀旅伴能查看這趟旅程與共同筆記。</span></aside><button className="page-primary"><Icon name="add"/>邀請旅伴</button></main>}
const paceOptions=['悠閒','輕鬆','適中','充實','緊湊'];
export function SettingsPage(){const {tripId}=useParams();const {data:trip}=useTrip(tripId);const {data:days=[]}=useTripDays(tripId);const [pace,setPace]=useState('適中');const [map,setMap]=useState('Naver');const [buffer,setBuffer]=useState(true);return <main className="settings-page"><header><h1>旅程設定</h1><p>{trip?.title} · {trip?.startDate}–{trip?.endDate}</p></header><div className="settings-body"><section><h2>全程步調</h2><p>每天預設為「適中」，也可逐日覆寫</p><div className="choice-row">{paceOptions.map(option=><button key={option} className={pace===option?'selected':''} onClick={()=>setPace(option)}>{option}</button>)}</div></section><section><h2>每日覆寫</h2>{days.map(day=><div className="daily-row" key={day.id}><span><b>Day {day.sortOrder}</b>{day.title}</span><strong>{day.sortOrder===1?'輕鬆':day.sortOrder===3?'充實':pace}</strong></div>)}</section><section><h2>韓國地圖服務</h2><div className="choice-row map-choice">{['Naver','Kakao','Google'].map(option=><button key={option} className={map===option?'selected green':''} onClick={()=>setMap(option)}>{option}</button>)}</div></section><section className="buffer-row"><span><h2>機場預留時間</h2><p>起飛前 3 小時抵達機場</p></span><button role="switch" aria-checked={buffer} className={buffer?'toggle on':'toggle'} onClick={()=>setBuffer(!buffer)}><i/></button></section><Link className="page-primary" to={`/trips/${tripId}/overview`}>儲存旅程設定</Link></div></main>}
export function BudgetPage(){const {tripId}=useParams();const {data:expenses=[]}=useExpenses(tripId);return <main className="budget-page"><header><h1>預算與分帳</h1><p>預估、實際支出與旅伴分攤</p></header><div className="budget-body"><section className="budget-summary"><div><span>旅程實際支出</span><b>KRW</b><small>TWD</small></div><strong>₩ 486,200</strong><p>約 NT$ 11,470 · 3 位旅伴</p><div className="budget-label"><span>預算 ₩ 800,000</span><b>61%</b></div><div className="progress"><i/></div></section><h2>最近支出</h2>{expenses.map(expense=><article className="expense-row" key={expense.id}><span><strong>{expense.title}</strong><small>{expense.meta}</small></span><span><strong>{expense.amount}</strong><small>{expense.split}</small></span></article>)}<p className="budget-note">預算僅旅伴可見，公開唯讀連結會自動隱藏。</p><button className="page-primary">新增支出</button><Link className="back-budget" to={`/trips/${tripId}/overview`}>返回旅程總覽</Link></div></main>}
