import { createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode } from 'react';
import type { AppError,ItineraryItem,SyncState } from '../contracts/entities';
import { hasSupabaseConfig } from '../lib/supabase';
import { mapSupabaseError, syncStateForError } from '../lib/supabaseError';
import { beginOptimistic, completeOptimistic, rollbackOptimistic } from './tripDataState';
import type { ItineraryRepository } from '../repositories/interfaces/ItineraryRepository';
import { MockItineraryRepository } from '../repositories/mock/MockItineraryRepository';
import { SupabaseItineraryRepository } from '../repositories/supabase/SupabaseItineraryRepository';
type TripDataValue={days:Record<string,ItineraryItem[]>;syncState:SyncState;error:AppError|null;loadDay:(dayId:string)=>Promise<void>;move:(dayId:string,from:number,to:number)=>Promise<void>;moveAcross:(sourceDayId:string,targetDayId:string,itemId:string,targetIndex:number)=>Promise<void>;addPlace:(dayId:string,item:ItineraryItem)=>Promise<void>;updateItem:(itemId:string,expectedVersion:number,patch:Partial<ItineraryItem>)=>Promise<void>;removeItem:(item:ItineraryItem)=>Promise<void>;retry:()=>Promise<void>};
const TripDataContext=createContext<TripDataValue|null>(null);
export function TripDataProvider({children}:{children:ReactNode}){
  const repository=useMemo<ItineraryRepository>(()=>hasSupabaseConfig?new SupabaseItineraryRepository():new MockItineraryRepository(),[]);const[days,setDays]=useState<Record<string,ItineraryItem[]>>({});const[syncState,setSyncState]=useState<SyncState>('synced');const[error,setError]=useState<AppError|null>(null);
  const loadDay=useCallback(async(dayId:string)=>{try{const items=await repository.list(dayId);setDays(value=>({...value,[dayId]:items}));setSyncState('synced');setError(null)}catch(cause){const appError=mapSupabaseError(cause);setSyncState(syncStateForError(appError));setError(appError)}},[repository]);
  const optimistic=useCallback(async(next:Record<string,ItineraryItem[]>,commit:()=>Promise<void>)=>{const previous=days;const pending=beginOptimistic(next);setDays(pending.data);setSyncState(pending.syncState);setError(pending.error);try{await commit();const settled=completeOptimistic(next);setSyncState(settled.syncState);setError(settled.error)}catch(cause){const rolledBack=rollbackOptimistic(previous,cause);setDays(rolledBack.data);setSyncState(rolledBack.syncState);setError(rolledBack.error);throw rolledBack.error}},[days]);
  const move=useCallback(async(dayId:string,from:number,to:number)=>{const current=days[dayId]??[];const next=[...current];const[item]=next.splice(from,1);if(!item)return;next.splice(to,0,item);await optimistic({...days,[dayId]:next},async()=>{const items=await repository.reorder(dayId,next.map(({id})=>id));setDays(value=>({...value,[dayId]:items}))})},[days,optimistic,repository]);
  const moveAcross=useCallback(async(sourceDayId:string,targetDayId:string,itemId:string,targetIndex:number)=>{const item=(days[sourceDayId]??[]).find(entry=>entry.id===itemId);if(!item||item.fixed)return;const source=(days[sourceDayId]??[]).filter(entry=>entry.id!==itemId);const target=[...(days[targetDayId]??[])];target.splice(targetIndex,0,{...item,tripDayId:targetDayId});await optimistic({...days,[sourceDayId]:source,[targetDayId]:target},()=>repository.moveAcross(item,targetDayId,targetIndex))},[days,optimistic,repository]);
  const addPlace=useCallback(async(dayId:string,item:ItineraryItem)=>{await optimistic({...days,[dayId]:[...(days[dayId]??[]),item]},async()=>{const items=await repository.add(dayId,item);setDays(value=>({...value,[dayId]:items}))})},[days,optimistic,repository]);
  const updateItem=useCallback(async(itemId:string,expectedVersion:number,patch:Partial<ItineraryItem>)=>{let current:ItineraryItem|undefined;let currentDay='';for(const[id,items]of Object.entries(days)){current=items.find(item=>item.id===itemId);if(current){currentDay=id;break}}if(!current)return;const updated={...current,...patch};await optimistic({...days,[currentDay]:days[currentDay].map(item=>item.id===itemId?updated:item)},async()=>{const saved=await repository.update(itemId,expectedVersion,patch);setDays(value=>({...value,[currentDay]:value[currentDay].map(item=>item.id===itemId?saved:item)}))})},[days,optimistic,repository]);
  const removeItem=useCallback(async(item:ItineraryItem)=>{await optimistic({...days,[item.tripDayId]:(days[item.tripDayId]??[]).filter(entry=>entry.id!==item.id)},()=>repository.remove(item))},[days,optimistic,repository]);
  const retry=useCallback(async()=>{await Promise.all(Object.keys(days).map(loadDay))},[days,loadDay]);
  useEffect(()=>{const ids=Object.keys(days);if(!ids.length)return;return repository.subscribe(ids,()=>{void Promise.all(ids.map(loadDay))})},[days,loadDay,repository]);
  return <TripDataContext.Provider value={{days,syncState,error,loadDay,move,moveAcross,addPlace,updateItem,removeItem,retry}}>{children}</TripDataContext.Provider>;
}
export function useTripData(){const value=useContext(TripDataContext);if(!value)throw new Error('TripDataProvider is required');return value}
