import { type KeyboardEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Icon } from '../../components/icons/Icon';
import { StatusNotice } from '../../components/primitives/Objects';
import { useAuth } from '../../app/AuthContext';
import { useTripData } from '../../app/TripDataContext';
import { useTripDays } from '../trips/queries';
import { nextAppendSortKey, toZonedIso } from '../places/itineraryPlanning';
import { addEventToItinerary, currentPlatformRole, discoveryRegions, getDiscovery, initialDiscoveryFilters, listDiscovery, reportEvent, reviewAction, type DiscoveryFilters, type DiscoveryItem, type DiscoveryKind } from './discoveryRepository';
import './discovery.css';

const trustLabel: Record<DiscoveryItem['trust'], string> = { official: '官方來源', verified: '已驗證', unverified: '未驗證', stale: '資料較舊' };
function TrustBadge({ value }: { value: DiscoveryItem['trust'] }) { return <span className={`trust-badge trust-badge--${value}`}><Icon name={value === 'official' || value === 'verified' ? 'success' : value === 'stale' ? 'warning' : 'info'} size={16}/>{trustLabel[value]}</span>; }
function Source({ item }: { item: DiscoveryItem }) { return item.source ? <section className="source-attribution" aria-label="資料來源"><strong>官方來源</strong><a href={item.source.url} target="_blank" rel="noreferrer">{item.source.name}</a><small>最後確認：{new Date(item.lastVerifiedAt || item.updatedAt).toLocaleDateString('zh-TW')}</small></section> : null; }
function PageHeader({ back, title }: { back: string; title: string }) { return <header className="discovery-header"><Link to={back}><Icon name="back" size={20}/>返回</Link><h1 tabIndex={-1}>{title}</h1></header>; }
function DiscoveryCard({ item, tripId }: { item: DiscoveryItem; tripId: string }) { return <article className="discovery-card"><Link className="discovery-card__main" to={`/trips/${tripId}/discover/${item.kind}/${item.id}`}><span className="discovery-card__kind"><Icon name={item.kind === 'event' ? 'calendar' : 'location'} size={20}/>{item.kind === 'event' ? '活動' : '景點'}</span><div><h2>{item.title}</h2><p>{item.koreanName}</p><small>{item.region} · {item.category}</small>{item.startsAt && <small>{new Date(item.startsAt).toLocaleString('zh-TW', { dateStyle: 'short', timeStyle: 'short' })}</small>}</div></Link><TrustBadge value={item.trust}/><Source item={item}/></article>; }

export function DiscoveryExplorePage() {
  const { tripId = '' } = useParams(); const [filters, setFilters] = useState<DiscoveryFilters>(initialDiscoveryFilters); const [cursor, setCursor] = useState<Parameters<typeof listDiscovery>[2]>({}); const [items, setItems] = useState<DiscoveryItem[]>([]); const [filterOpen, setFilterOpen] = useState(false); const filterButton = useRef<HTMLButtonElement>(null);
  const result = useQuery({ queryKey: ['discovery', filters, cursor], queryFn: () => listDiscovery(filters, 24, cursor) });
  useEffect(() => { if (result.data) setItems(current => cursor && (cursor.events || cursor.places) ? [...current, ...result.data.items] : result.data.items); }, [result.data, cursor]);
  useEffect(() => { if (!filterOpen) filterButton.current?.focus(); }, [filterOpen]);
  const reset = (next: DiscoveryFilters) => { setItems([]); setCursor({}); setFilters(next); };
  return <main className="discovery-page"><PageHeader title="探索活動與景點" back={`/trips/${tripId}/plan`}/><section className="discovery-toolbar"><label><span className="sr-only">搜尋活動或景點</span><input value={filters.query} onChange={(event) => reset({ ...filters, query: event.target.value })} placeholder="搜尋活動、景點或區域"/></label><button ref={filterButton} className="filter-trigger" onClick={() => setFilterOpen(true)}><Icon name="filter" size={20}/>篩選</button></section><div className="discovery-tabs" role="tablist"><button role="tab" aria-selected={filters.kind !== 'place'} onClick={() => reset({ ...filters, kind: filters.kind === 'event' ? 'all' : 'event' })}>活動</button><button role="tab" aria-selected={filters.kind !== 'event'} onClick={() => reset({ ...filters, kind: filters.kind === 'place' ? 'all' : 'place' })}>景點</button></div>{filterOpen && <section className="filter-sheet" role="dialog" aria-modal="true" aria-labelledby="filter-title"><div><h2 id="filter-title" tabIndex={-1}>篩選探索結果</h2><label>區域<select value={filters.region} onChange={(event) => setFilters({ ...filters, region: event.target.value })}>{discoveryRegions.map(region => <option key={region.code} value={region.code}>{region.label}</option>)}</select></label><label>開始日期<input type="date" value={filters.startDate || ''} onChange={event => setFilters({ ...filters, startDate: event.target.value })}/></label><label>結束日期<input type="date" value={filters.endDate || ''} onChange={event => setFilters({ ...filters, endDate: event.target.value })}/></label><label>類型<input value={filters.category || ''} onChange={event => setFilters({ ...filters, category: event.target.value })} placeholder="例如 festival"/></label><label><input type="checkbox" checked={filters.verifiedOnly} onChange={(event) => setFilters({ ...filters, verifiedOnly: event.target.checked })}/>只看已驗證資料</label><button onClick={() => { setItems([]); setCursor({}); setFilterOpen(false); }}>套用篩選</button></div></section>}<p className="discovery-result-count" role="status">{items.length} 筆結果</p><section className="discovery-grid" aria-live="polite">{result.isLoading && !items.length && <p className="discovery-state">正在載入官方資料…</p>}{result.isError && <p className="discovery-state is-error">官方資料暫時無法取得。<button onClick={() => void result.refetch()}>再試一次</button></p>}{!result.isLoading && !result.isError && !items.length && <p className="discovery-state">目前沒有符合條件的已發布資料。</p>}{items.map((item) => <DiscoveryCard key={`${item.kind}-${item.id}`} item={item} tripId={tripId}/>)}</section>{result.data?.next && <button className="load-more" disabled={result.isFetching} onClick={() => setCursor(result.data?.next || {})}>{result.isFetching ? '正在載入…' : '載入更多'}</button>}{!result.isLoading && !result.data?.next && items.length > 0 && <p className="discovery-end">已載入所有結果。</p>}</main>;
}

export function DiscoveryDetailPage() {
  const { tripId = '', kind = 'event', id = '' } = useParams(); const entityKind = kind as DiscoveryKind; const { user } = useAuth(); const [reportOpen, setReportOpen] = useState(false); const [reportState, setReportState] = useState<'idle' | 'saving' | 'success' | 'error'>('idle'); const [details, setDetails] = useState(''); const query = useQuery({ queryKey: ['discovery-detail', entityKind, id], queryFn: () => getDiscovery(entityKind, id) }); const navigate = useNavigate();
  if (query.isLoading) return <main className="discovery-page"><PageHeader title="載入資料" back={`/trips/${tripId}/discover`}/><p className="discovery-state">正在載入…</p></main>;
  if (query.isError || !query.data) return <main className="discovery-page"><PageHeader title="找不到資料" back={`/trips/${tripId}/discover`}/><p className="discovery-state is-error">資料目前無法使用。<button onClick={() => void query.refetch()}>再試一次</button></p></main>;
  const item = query.data; const submitReport = async () => { if (!user || item.kind !== 'event') return; setReportState('saving'); try { await reportEvent(item.id, 'incorrect_information', details, user.id || ''); setReportState('success'); } catch { setReportState('error'); } };
  return <main className="discovery-page discovery-detail"><PageHeader title={item.kind === 'event' ? '活動詳情' : '景點詳情'} back={`/trips/${tripId}/discover`}/><section className="detail-card"><TrustBadge value={item.trust}/><h2>{item.title}</h2><p className="korean-name">{item.koreanName}</p>{item.kind === 'event' && <p>{item.startsAt && new Date(item.startsAt).toLocaleString('zh-TW')} 至 {item.endsAt && new Date(item.endsAt).toLocaleString('zh-TW')}</p>}{item.venue && <p>{item.venue}</p>}{item.address && <p>{item.address}</p>}<p>{item.description || '官方來源尚未提供更多說明。'}</p><Source item={item}/>{item.trust === 'stale' && <StatusNotice type="warning" title="來源資訊已更新">你的既有行程不會被自動改寫；請查看官方來源後自行決定。</StatusNotice>}<div className="detail-actions">{item.kind === 'event' ? <button onClick={() => navigate(`/trips/${tripId}/discover/event/${item.id}/add`)} disabled={Boolean(item.disabledReason)}>{item.disabledReason || '加入行程'}</button> : <Link to={`/trips/${tripId}/plan/add/${item.id}`}>加入行程</Link>}{user && <button className="secondary" onClick={() => setReportOpen(true)}>回報資料問題</button>}</div></section>{reportOpen && <section className="filter-sheet" role="dialog" aria-modal="true" aria-labelledby="report-title"><div><h2 id="report-title" tabIndex={-1}>回報資料問題</h2>{item.kind === 'place' ? <p>此景點目前尚未提供可提交的回報 DTO。</p> : <><label>問題說明<textarea value={details} onChange={(event) => setDetails(event.target.value)} placeholder="請勿輸入行程或其他敏感資料。"/></label>{reportState === 'error' && <p role="alert">送出失敗，內容已保留，可再試一次。</p>}{reportState === 'success' ? <p role="status">已送交審核。</p> : <button disabled={reportState === 'saving'} onClick={() => void submitReport()}>{reportState === 'saving' ? '正在送出…' : '送交審核'}</button>}</>}<button className="secondary" onClick={() => setReportOpen(false)}>關閉</button></div></section>}</main>;
}

export function AddEventPage() {
  const { tripId = '', id = '' } = useParams(); const { data: days = [] } = useTripDays(tripId); const { days: itineraryDays } = useTripData(); const navigate = useNavigate(); const queryClient = useQueryClient(); const [dayId, setDayId] = useState(''); const [time, setTime] = useState('10:00'); const [state, setState] = useState<'idle' | 'saving' | 'success' | 'conflict' | 'error'>('idle'); const activeDay = dayId || days[0]?.id || ''; const selectedDay = days.find((day) => day.id === activeDay);
  const submit = async () => { if (!selectedDay) return; setState('saving'); try { await addEventToItinerary(id, activeDay, toZonedIso(selectedDay.date, time, 'Asia/Seoul'), 60, nextAppendSortKey(itineraryDays[activeDay] || []), crypto.randomUUID()); setState('success'); await queryClient.invalidateQueries({ queryKey: ['itinerary', activeDay] }); } catch (error: unknown) { const hint = typeof error === 'object' && error && 'hint' in error ? String(error.hint) : ''; const code = typeof error === 'object' && error && 'code' in error ? String(error.code) : ''; setState(code === 'PT409' || hint.includes('ITINERARY_TIME_CONFLICT') ? 'conflict' : 'error'); } };
  return <main className="discovery-page"><PageHeader title="加入行程" back={`/trips/${tripId}/discover/event/${id}`}/><section className="add-sheet"><p>加入時會保存來源參考與當下 snapshot，未來來源變更只會通知你。</p><label>旅程日<select value={activeDay} onChange={(event) => setDayId(event.target.value)}>{days.map((day) => <option key={day.id} value={day.id}>Day {day.sortOrder} · {day.date}</option>)}</select></label><label>開始時間<input type="time" value={time} onChange={(event) => setTime(event.target.value)}/></label>{state === 'conflict' && <StatusNotice type="conflict" title="時間發生衝突">不會覆寫既有行程。請改時間或查看行程。</StatusNotice>}{state === 'error' && <StatusNotice type="warning" title="加入失敗">原行程沒有變更，請再試一次。</StatusNotice>}{state === 'success' && <StatusNotice type="success" title="已加入行程">已加入第 {selectedDay?.sortOrder} 天。<Link to={`/trips/${tripId}/plan?day=${activeDay}`}>查看行程</Link></StatusNotice>}<button disabled={!selectedDay || state === 'saving'} onClick={() => void submit()}>{state === 'saving' ? '正在加入…' : '加入行程'}</button>{state === 'conflict' && <button className="secondary" onClick={() => navigate(`/trips/${tripId}/plan?day=${activeDay}`)}>查看行程</button>}</section></main>;
}

export function ReviewerQueuePage() {
  const role = useQuery({ queryKey: ['platform-role'], queryFn: currentPlatformRole }); const [selected, setSelected] = useState<{ id: string; kind: DiscoveryKind; decision: 'approve' | 'request_changes' | 'reject' | 'publish' } | null>(null); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const [failure, setFailure] = useState(false); const [success, setSuccess] = useState(''); const triggerRef = useRef<HTMLButtonElement>(null); const confirmRef = useRef<HTMLButtonElement>(null); const dialogRef = useRef<HTMLElement>(null); const queue = useQuery({ queryKey: ['review-queue'], enabled: Boolean(role.data), queryFn: async () => { const { supabase } = await import('../../lib/supabase'); if (!supabase) return []; const { data, error } = await supabase.from('data_review_queue').select('*').in('status', ['pending', 'needs_changes', 'approved']).order('priority', { ascending: false }); if (error) throw error; return data; } });
  useEffect(() => { if (selected) window.requestAnimationFrame(() => confirmRef.current?.focus()); }, [selected]);
  if (role.isLoading) return <main className="discovery-page"><p className="discovery-state">正在確認權限…</p></main>;
  if (!role.data) return <main className="discovery-page"><PageHeader title="審核佇列" back="/trips"/><p className="discovery-state is-error" role="alert">403：你沒有資料審核權限。</p></main>;
  const closeDialog = () => { setSelected(null); setFailure(false); window.requestAnimationFrame(() => triggerRef.current?.focus()); };
  const run = async () => { if (!selected) return; setSaving(true); setFailure(false); try { await reviewAction(selected.id, selected.kind, selected.decision, note); setSuccess('審核動作已送出。'); setNote(''); closeDialog(); await queue.refetch(); } catch { setFailure(true); } finally { setSaving(false); } };
  const trapDialogFocus = (event: KeyboardEvent<HTMLElement>) => { if (event.key === 'Escape' && !saving) { event.preventDefault(); closeDialog(); return; } if (event.key !== 'Tab' || !dialogRef.current) return; const focusables = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), textarea:not([disabled]), [href]')); if (!focusables.length) return; const first = focusables[0]; const last = focusables.at(-1)!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
  return <main className="discovery-page reviewer-queue"><PageHeader title="資料審核佇列" back="/trips"/>{success && <p className="discovery-state" role="status">{success}</p>}{queue.isLoading && <p className="discovery-state">正在載入待審資料…</p>}{queue.isError && <p className="discovery-state is-error">無法載入審核佇列。<button onClick={() => void queue.refetch()}>再試一次</button></p>}{!queue.isLoading && !queue.data?.length && <p className="discovery-state">目前沒有待審資料。</p>}{queue.data?.map((item) => { const targetId = item.event_id || item.place_id; const targetKind: DiscoveryKind = item.event_id ? 'event' : 'place'; return <article key={item.id} className="review-row"><div><strong>{targetKind === 'event' ? '活動' : '景點'} · 優先級 {item.priority}</strong><small>風險：{item.risk_flags.join('、') || '無'} · {item.status}</small></div>{(['approve', 'request_changes', 'reject', 'publish'] as const).map((decision) => <button key={decision} disabled={!targetId || (decision === 'publish' && item.status !== 'approved')} onClick={(event) => { if (!targetId) return; triggerRef.current = event.currentTarget; setFailure(false); setSelected({ id: targetId, kind: targetKind, decision }); }}>{decision === 'approve' ? '核准' : decision === 'request_changes' ? '要求修正' : decision === 'reject' ? '拒絕' : '發布'}</button>)}</article>; })}{selected && <section ref={dialogRef} className="filter-sheet" role="dialog" aria-modal="true" aria-labelledby="review-confirm-title" onKeyDown={trapDialogFocus}><div><h2 id="review-confirm-title" tabIndex={-1}>確認審核動作</h2><label>審核備註<textarea value={note} onChange={(event) => setNote(event.target.value)}/></label>{failure && <p role="alert">更新失敗，備註已保留，請再試一次。</p>}<button ref={confirmRef} disabled={saving} onClick={() => void run()}>{saving ? '正在更新…' : failure ? '再試一次' : '確認'}</button><button className="secondary" disabled={saving} onClick={closeDialog}>取消</button></div></section>}</main>;
}
